package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

/**
 * FaseLoteId generated by hbm2java
 */
@Embeddable
public class FaseLoteId implements java.io.Serializable {

	private int codLote;
	private int codItem;
	private int codFase;

	public FaseLoteId() {
	}

	public FaseLoteId(int codLote, int codItem, int codFase) {
		this.codLote = codLote;
		this.codItem = codItem;
		this.codFase = codFase;
	}

	@Column(name = "cod_lote", nullable = false)
	public int getCodLote() {
		return this.codLote;
	}

	public void setCodLote(int codLote) {
		this.codLote = codLote;
	}

	@Column(name = "cod_item", nullable = false)
	public int getCodItem() {
		return this.codItem;
	}

	public void setCodItem(int codItem) {
		this.codItem = codItem;
	}

	@Column(name = "cod_fase", nullable = false)
	public int getCodFase() {
		return this.codFase;
	}

	public void setCodFase(int codFase) {
		this.codFase = codFase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FaseLoteId))
			return false;
		FaseLoteId castOther = (FaseLoteId) other;

		return (this.getCodLote() == castOther.getCodLote()) && (this.getCodItem() == castOther.getCodItem())
				&& (this.getCodFase() == castOther.getCodFase());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLote();
		result = 37 * result + this.getCodItem();
		result = 37 * result + this.getCodFase();
		return result;
	}

}
