package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * Fase generated by hbm2java
 */
@Entity
@Table(name = "fase", catalog = "projetoSistemas")
public class Fase implements java.io.Serializable {

	private Integer codFase;
	private String nomeFase;
	private String observacao;
	private char flagProcriacao;

	public Fase() {
	}

	public Fase(String nomeFase, char flagProcriacao) {
		this.nomeFase = nomeFase;
		this.flagProcriacao = flagProcriacao;
	}

	public Fase(String nomeFase, String observacao, char flagProcriacao) {
		this.nomeFase = nomeFase;
		this.observacao = observacao;
		this.flagProcriacao = flagProcriacao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cod_fase", unique = true, nullable = false)
	public Integer getCodFase() {
		return this.codFase;
	}

	public void setCodFase(Integer codFase) {
		this.codFase = codFase;
	}

	@Column(name = "nome_fase", nullable = false, length = 50)
	public String getNomeFase() {
		return this.nomeFase;
	}

	public void setNomeFase(String nomeFase) {
		this.nomeFase = nomeFase;
	}

	@Column(name = "observacao", length = 500)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "flag_procriacao", nullable = false, length = 1)
	public char getFlagProcriacao() {
		return this.flagProcriacao;
	}

	public void setFlagProcriacao(char flagProcriacao) {
		this.flagProcriacao = flagProcriacao;
	}

}
