package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GadoPesagemId generated by hbm2java
 */
@Embeddable
public class GadoPesagemId implements java.io.Serializable {

	private int codPesagem;
	private int codGado;

	public GadoPesagemId() {
	}

	public GadoPesagemId(int codPesagem, int codGado) {
		this.codPesagem = codPesagem;
		this.codGado = codGado;
	}

	@Column(name = "cod_pesagem", nullable = false)
	public int getCodPesagem() {
		return this.codPesagem;
	}

	public void setCodPesagem(int codPesagem) {
		this.codPesagem = codPesagem;
	}

	@Column(name = "cod_gado", nullable = false)
	public int getCodGado() {
		return this.codGado;
	}

	public void setCodGado(int codGado) {
		this.codGado = codGado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GadoPesagemId))
			return false;
		GadoPesagemId castOther = (GadoPesagemId) other;

		return (this.getCodPesagem() == castOther.getCodPesagem()) && (this.getCodGado() == castOther.getCodGado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodPesagem();
		result = 37 * result + this.getCodGado();
		return result;
	}

}
