package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * Gado generated by hbm2java
 */
@Entity
@Table(name = "gado", catalog = "projetoSistemas")
public class Gado implements java.io.Serializable {

	private Integer codGado;
	private int codRaca;
	private Date dataNascimento;
	private String localNascimento;
	private String observacao;
	private Integer codSisbov;
	private Integer racaPai;
	private Integer racaMae;
	private Character flagProcedencia;
	private Character flagStatus;
	private Character sexualidade;

	public Gado() {
	}

	public Gado(int codRaca, Date dataNascimento) {
		this.codRaca = codRaca;
		this.dataNascimento = dataNascimento;
	}

	public Gado(int codRaca, Date dataNascimento, String localNascimento, String observacao, Integer codSisbov,
			Integer racaPai, Integer racaMae, Character flagProcedencia, Character flagStatus, Character sexualidade) {
		this.codRaca = codRaca;
		this.dataNascimento = dataNascimento;
		this.localNascimento = localNascimento;
		this.observacao = observacao;
		this.codSisbov = codSisbov;
		this.racaPai = racaPai;
		this.racaMae = racaMae;
		this.flagProcedencia = flagProcedencia;
		this.flagStatus = flagStatus;
		this.sexualidade = sexualidade;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "cod_gado", unique = true, nullable = false)
	public Integer getCodGado() {
		return this.codGado;
	}

	public void setCodGado(Integer codGado) {
		this.codGado = codGado;
	}

	@Column(name = "cod_raca", nullable = false)
	public int getCodRaca() {
		return this.codRaca;
	}

	public void setCodRaca(int codRaca) {
		this.codRaca = codRaca;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", nullable = false, length = 10)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "local_nascimento", length = 100)
	public String getLocalNascimento() {
		return this.localNascimento;
	}

	public void setLocalNascimento(String localNascimento) {
		this.localNascimento = localNascimento;
	}

	@Column(name = "observacao", length = 250)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "cod_sisbov")
	public Integer getCodSisbov() {
		return this.codSisbov;
	}

	public void setCodSisbov(Integer codSisbov) {
		this.codSisbov = codSisbov;
	}

	@Column(name = "raca_pai")
	public Integer getRacaPai() {
		return this.racaPai;
	}

	public void setRacaPai(Integer racaPai) {
		this.racaPai = racaPai;
	}

	@Column(name = "raca_mae")
	public Integer getRacaMae() {
		return this.racaMae;
	}

	public void setRacaMae(Integer racaMae) {
		this.racaMae = racaMae;
	}

	@Column(name = "flag_procedencia", length = 1)
	public Character getFlagProcedencia() {
		return this.flagProcedencia;
	}

	public void setFlagProcedencia(Character flagProcedencia) {
		this.flagProcedencia = flagProcedencia;
	}

	@Column(name = "flag_status", length = 1)
	public Character getFlagStatus() {
		return this.flagStatus;
	}

	public void setFlagStatus(Character flagStatus) {
		this.flagStatus = flagStatus;
	}

	@Column(name = "sexualidade", length = 1)
	public Character getSexualidade() {
		return this.sexualidade;
	}

	public void setSexualidade(Character sexualidade) {
		this.sexualidade = sexualidade;
	}

}
