package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * GadoPesagem generated by hbm2java
 */
@Entity
@Table(name = "gado_pesagem", catalog = "projetoSistemas")
public class GadoPesagem implements java.io.Serializable {

	private GadoPesagemId id;
	private Date dataPesagem;
	private BigDecimal peso;

	public GadoPesagem() {
	}

	public GadoPesagem(GadoPesagemId id) {
		this.id = id;
	}

	public GadoPesagem(GadoPesagemId id, Date dataPesagem, BigDecimal peso) {
		this.id = id;
		this.dataPesagem = dataPesagem;
		this.peso = peso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codPesagem", column = @Column(name = "cod_pesagem", nullable = false) ),
			@AttributeOverride(name = "codGado", column = @Column(name = "cod_gado", nullable = false) ) })
	public GadoPesagemId getId() {
		return this.id;
	}

	public void setId(GadoPesagemId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_pesagem", length = 19)
	public Date getDataPesagem() {
		return this.dataPesagem;
	}

	public void setDataPesagem(Date dataPesagem) {
		this.dataPesagem = dataPesagem;
	}

	@Column(name = "peso", precision = 5)
	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

}
