package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoteAlimentacaoId generated by hbm2java
 */
@Embeddable
public class LoteAlimentacaoId implements java.io.Serializable {

	private int codLote;
	private int seqItem;

	public LoteAlimentacaoId() {
	}

	public LoteAlimentacaoId(int codLote, int seqItem) {
		this.codLote = codLote;
		this.seqItem = seqItem;
	}

	@Column(name = "cod_lote", nullable = false)
	public int getCodLote() {
		return this.codLote;
	}

	public void setCodLote(int codLote) {
		this.codLote = codLote;
	}

	@Column(name = "seq_item", nullable = false)
	public int getSeqItem() {
		return this.seqItem;
	}

	public void setSeqItem(int seqItem) {
		this.seqItem = seqItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoteAlimentacaoId))
			return false;
		LoteAlimentacaoId castOther = (LoteAlimentacaoId) other;

		return (this.getCodLote() == castOther.getCodLote()) && (this.getSeqItem() == castOther.getSeqItem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLote();
		result = 37 * result + this.getSeqItem();
		return result;
	}

}
