package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * LoteAlimentacao generated by hbm2java
 */
@Entity
@Table(name = "lote_alimentacao", catalog = "projetoSistemas")
public class LoteAlimentacao implements java.io.Serializable {

	private LoteAlimentacaoId id;
	private int codAlimentacao;
	private Date dataInicio;
	private Date dataPrevistoFim;
	private Date dataFim;
	private BigDecimal pesoInicialLote;
	private BigDecimal pesoFinalLote;
	private char flagAtivo;

	public LoteAlimentacao() {
	}

	public LoteAlimentacao(LoteAlimentacaoId id, int codAlimentacao, char flagAtivo) {
		this.id = id;
		this.codAlimentacao = codAlimentacao;
		this.flagAtivo = flagAtivo;
	}

	public LoteAlimentacao(LoteAlimentacaoId id, int codAlimentacao, Date dataInicio, Date dataPrevistoFim,
			Date dataFim, BigDecimal pesoInicialLote, BigDecimal pesoFinalLote, char flagAtivo) {
		this.id = id;
		this.codAlimentacao = codAlimentacao;
		this.dataInicio = dataInicio;
		this.dataPrevistoFim = dataPrevistoFim;
		this.dataFim = dataFim;
		this.pesoInicialLote = pesoInicialLote;
		this.pesoFinalLote = pesoFinalLote;
		this.flagAtivo = flagAtivo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codLote", column = @Column(name = "cod_lote", nullable = false) ),
			@AttributeOverride(name = "seqItem", column = @Column(name = "seq_item", nullable = false) ) })
	public LoteAlimentacaoId getId() {
		return this.id;
	}

	public void setId(LoteAlimentacaoId id) {
		this.id = id;
	}

	@Column(name = "cod_alimentacao", nullable = false)
	public int getCodAlimentacao() {
		return this.codAlimentacao;
	}

	public void setCodAlimentacao(int codAlimentacao) {
		this.codAlimentacao = codAlimentacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_inicio", length = 10)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_previstoFim", length = 10)
	public Date getDataPrevistoFim() {
		return this.dataPrevistoFim;
	}

	public void setDataPrevistoFim(Date dataPrevistoFim) {
		this.dataPrevistoFim = dataPrevistoFim;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_fim", length = 10)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@Column(name = "peso_inicialLote", precision = 5)
	public BigDecimal getPesoInicialLote() {
		return this.pesoInicialLote;
	}

	public void setPesoInicialLote(BigDecimal pesoInicialLote) {
		this.pesoInicialLote = pesoInicialLote;
	}

	@Column(name = "peso_finalLote", precision = 5)
	public BigDecimal getPesoFinalLote() {
		return this.pesoFinalLote;
	}

	public void setPesoFinalLote(BigDecimal pesoFinalLote) {
		this.pesoFinalLote = pesoFinalLote;
	}

	@Column(name = "flag_ativo", nullable = false, length = 1)
	public char getFlagAtivo() {
		return this.flagAtivo;
	}

	public void setFlagAtivo(char flagAtivo) {
		this.flagAtivo = flagAtivo;
	}

}
