package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

/**
 * LoteGadoId generated by hbm2java
 */
@Embeddable
public class LoteGadoId implements java.io.Serializable {

	private int codLote;
	private int codGado;

	public LoteGadoId() {
	}

	public LoteGadoId(int codLote, int codGado) {
		this.codLote = codLote;
		this.codGado = codGado;
	}

	@Column(name = "cod_lote", nullable = false)
	public int getCodLote() {
		return this.codLote;
	}

	public void setCodLote(int codLote) {
		this.codLote = codLote;
	}

	@Column(name = "cod_gado", nullable = false)
	public int getCodGado() {
		return this.codGado;
	}

	public void setCodGado(int codGado) {
		this.codGado = codGado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoteGadoId))
			return false;
		LoteGadoId castOther = (LoteGadoId) other;

		return (this.getCodLote() == castOther.getCodLote()) && (this.getCodGado() == castOther.getCodGado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLote();
		result = 37 * result + this.getCodGado();
		return result;
	}

}
