package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import java.util.Date;

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * LoteGado generated by hbm2java
 */
@Entity
@Table(name = "lote_gado", catalog = "projetoSistemas")
public class LoteGado implements java.io.Serializable {

	private LoteGadoId id;
	private Date dataInclusao;
	private Date dataExclusao;

	public LoteGado() {
	}

	public LoteGado(LoteGadoId id) {
		this.id = id;
	}

	public LoteGado(LoteGadoId id, Date dataInclusao, Date dataExclusao) {
		this.id = id;
		this.dataInclusao = dataInclusao;
		this.dataExclusao = dataExclusao;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codLote", column = @Column(name = "cod_lote", nullable = false) ),
			@AttributeOverride(name = "codGado", column = @Column(name = "cod_gado", nullable = false) ) })
	public LoteGadoId getId() {
		return this.id;
	}

	public void setId(LoteGadoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 19)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 19)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

}
