package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;  
import javax.persistence.Entity;  
/**
 * Medicamento generated by hbm2java
 */
@Entity
@Table(name = "medicamento", catalog = "projetoSistemas")
public class Medicamento implements java.io.Serializable {

	private Integer codMedicamento;
	private String nomeMedicamento;

	public Medicamento() {
	}

	public Medicamento(String nomeMedicamento) {
		this.nomeMedicamento = nomeMedicamento;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "cod_medicamento", unique = true, nullable = false)
	public Integer getCodMedicamento() {
		return this.codMedicamento;
	}

	public void setCodMedicamento(Integer codMedicamento) {
		this.codMedicamento = codMedicamento;
	}

	@Column(name = "nome_medicamento", nullable = false, length = 100)
	public String getNomeMedicamento() {
		return this.nomeMedicamento;
	}

	public void setNomeMedicamento(String nomeMedicamento) {
		this.nomeMedicamento = nomeMedicamento;
	}

}
