package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * Pecuarista generated by hbm2java
 */
@Entity
@Table(name = "pecuarista", catalog = "projetoSistemas")
public class Pecuarista implements java.io.Serializable {

	private int codPessoa;

	public Pecuarista() {
	}

	public Pecuarista(int codPessoa) {
		this.codPessoa = codPessoa;
	}

	@Id

	@Column(name = "cod_pessoa", unique = true, nullable = false)
	public int getCodPessoa() {
		return this.codPessoa;
	}

	public void setCodPessoa(int codPessoa) {
		this.codPessoa = codPessoa;
	}

}
