package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Id;

import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * PessoaFisica generated by hbm2java
 */
@Entity
@Table(name = "pessoa_fisica", catalog = "projetoSistemas")
public class PessoaFisica implements java.io.Serializable {

	private int codPessoa;
	private String numCpf;
	private String numRg;

	public PessoaFisica() {
	}

	public PessoaFisica(int codPessoa, String numCpf, String numRg) {
		this.codPessoa = codPessoa;
		this.numCpf = numCpf;
		this.numRg = numRg;
	}

	@Id

	@Column(name = "cod_pessoa", unique = true, nullable = false)
	public int getCodPessoa() {
		return this.codPessoa;
	}

	public void setCodPessoa(int codPessoa) {
		this.codPessoa = codPessoa;
	}

	@Column(name = "num_cpf", nullable = false, length = 11)
	public String getNumCpf() {
		return this.numCpf;
	}

	public void setNumCpf(String numCpf) {
		this.numCpf = numCpf;
	}

	@Column(name = "num_rg", nullable = false, length = 15)
	public String getNumRg() {
		return this.numRg;
	}

	public void setNumRg(String numRg) {
		this.numRg = numRg;
	}

}
