package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * ProdutoAlimenticio generated by hbm2java
 */
@Entity
@Table(name = "produto_alimenticio", catalog = "projetoSistemas")
public class ProdutoAlimenticio implements java.io.Serializable {

	private Integer codProduto;
	private int codPessoa;
	private String nomeProduto;
	private String observacaoComposicao;
	private Date dataValidade;

	public ProdutoAlimenticio() {
	}

	public ProdutoAlimenticio(int codPessoa) {
		this.codPessoa = codPessoa;
	}

	public ProdutoAlimenticio(int codPessoa, String nomeProduto, String observacaoComposicao, Date dataValidade) {
		this.codPessoa = codPessoa;
		this.nomeProduto = nomeProduto;
		this.observacaoComposicao = observacaoComposicao;
		this.dataValidade = dataValidade;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "cod_produto", unique = true, nullable = false)
	public Integer getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(Integer codProduto) {
		this.codProduto = codProduto;
	}

	@Column(name = "cod_pessoa", nullable = false)
	public int getCodPessoa() {
		return this.codPessoa;
	}

	public void setCodPessoa(int codPessoa) {
		this.codPessoa = codPessoa;
	}

	@Column(name = "nome_produto", length = 150)
	public String getNomeProduto() {
		return this.nomeProduto;
	}

	public void setNomeProduto(String nomeProduto) {
		this.nomeProduto = nomeProduto;
	}

	@Column(name = "observacao_composicao", length = 500)
	public String getObservacaoComposicao() {
		return this.observacaoComposicao;
	}

	public void setObservacaoComposicao(String observacaoComposicao) {
		this.observacaoComposicao = observacaoComposicao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_validade", length = 10)
	public Date getDataValidade() {
		return this.dataValidade;
	}

	public void setDataValidade(Date dataValidade) {
		this.dataValidade = dataValidade;
	}

}
