package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;

import javax.persistence.Table;  
import javax.persistence.Entity;  

/**
 * TipoAlimentacaoProduto generated by hbm2java
 */
@Entity
@Table(name = "tipo_alimentacao_produto", catalog = "projetoSistemas")
public class TipoAlimentacaoProduto implements java.io.Serializable {

	private TipoAlimentacaoProdutoId id;
	private String descricaoComposicao;
	private String loteProduto;
	private String observacao;

	public TipoAlimentacaoProduto() {
	}

	public TipoAlimentacaoProduto(TipoAlimentacaoProdutoId id) {
		this.id = id;
	}

	public TipoAlimentacaoProduto(TipoAlimentacaoProdutoId id, String descricaoComposicao, String loteProduto,
			String observacao) {
		this.id = id;
		this.descricaoComposicao = descricaoComposicao;
		this.loteProduto = loteProduto;
		this.observacao = observacao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codAlimentacao", column = @Column(name = "cod_alimentacao", nullable = false) ),
			@AttributeOverride(name = "codProduto", column = @Column(name = "cod_produto", nullable = false) ),
			@AttributeOverride(name = "seqItem", column = @Column(name = "seq_item", nullable = false) ) })
	public TipoAlimentacaoProdutoId getId() {
		return this.id;
	}

	public void setId(TipoAlimentacaoProdutoId id) {
		this.id = id;
	}

	@Column(name = "descricao_composicao", length = 500)
	public String getDescricaoComposicao() {
		return this.descricaoComposicao;
	}

	public void setDescricaoComposicao(String descricaoComposicao) {
		this.descricaoComposicao = descricaoComposicao;
	}

	@Column(name = "lote_produto", length = 15)
	public String getLoteProduto() {
		return this.loteProduto;
	}

	public void setLoteProduto(String loteProduto) {
		this.loteProduto = loteProduto;
	}

	@Column(name = "observacao", length = 500)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
