package com.sysbovino.entidades;
// Generated 07/10/2015 20:17:36 by Hibernate Tools 4.0.0

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * UnidadeFederativa generated by hbm2java
 */
@Entity
@Table(name = "unidade_federativa", catalog = "projetoSistemas")
public class UnidadeFederativa implements java.io.Serializable {

	private int codUf;
	private int codPais;
	private String nomeUf;
	private String abrevUf;

	public UnidadeFederativa() {
	}

	public UnidadeFederativa(int codUf, int codPais, String nomeUf, String abrevUf) {
		this.codUf = codUf;
		this.codPais = codPais;
		this.nomeUf = nomeUf;
		this.abrevUf = abrevUf;
	}

	@Id

	@Column(name = "cod_uf", unique = true, nullable = false)
	public int getCodUf() {
		return this.codUf;
	}

	public void setCodUf(int codUf) {
		this.codUf = codUf;
	}

	@Column(name = "cod_pais", nullable = false)
	public int getCodPais() {
		return this.codPais;
	}

	public void setCodPais(int codPais) {
		this.codPais = codPais;
	}

	@Column(name = "nome_uf", nullable = false, length = 150)
	public String getNomeUf() {
		return this.nomeUf;
	}

	public void setNomeUf(String nomeUf) {
		this.nomeUf = nomeUf;
	}

	@Column(name = "abrev_uf", nullable = false, length = 2)
	public String getAbrevUf() {
		return this.abrevUf;
	}

	public void setAbrevUf(String abrevUf) {
		this.abrevUf = abrevUf;
	}

}
